---
title: "Untitled"
author: "Steve Condylios"
date: "02/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(quantmod)
library(tidyverse)
```

## Plot Aud Vs USD/EUR over the last 10 years



```{r}

getFX("AUD/USD",from="2005-01-01")


symbols <- c(
  "UUP",
  "FXB",
  "FXE",
  "FXF",
  "FXY",
  "SLV",
  "GLD"
)

getSymbols(symbols, from="2004-01-01")

prices <- list()
for(i in 1:length(symbols)) {
  prices[[i]] <- Cl(get(symbols[i]))  
}

aud <- do.call(rbind, lapply(0:2, function(i) {
  getFX("AUD/USD", 
        from = Sys.Date() - 499 * (i + 1),
        to = Sys.Date() - 499 * i,
        env=NULL)
}))

prices <- do.call(cbind, c(prices, list(aud)))



prices %>%
  as.data.frame %>% 
  tibble::rownames_to_column("dates") %>% 
  select(dates, AUD.USD) %>% 
  ggplot(aes(x = dates, y = AUD.USD)) +
  geom_smooth()





```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.












